CREATE TABLE IF NOT EXISTS posts (
	id INT AUTO_INCREMENT primary key,
	title VARCHAR(200),
	content TEXT,
	category VARCHAR(100),
	created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	status VARCHAR(100)
);